spring.application.name=modulo-a-gateway

# --- BANCO DE DADOS (SUPABASE) ---
# Limpamos os parâmetros extras da URL para o Spring usar as propriedades abaixo
# Alteramos a porta de 5432 para 6543
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.uukodziqxvnajhucspda
spring.datasource.password=DatabaseANBIMA1234!

# Adicione estas linhas para garantir que o Java não desista da conexão
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# Força o Hibernate a entender que é um PostgreSQL (ajuda a evitar o erro de Dialect)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- SERVIDOR ---
server.port=${PORT:8080}

# --- MENSAGERIA (CLOUDAMQP) ---
spring.rabbitmq.host=guppy.rmq6.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=bqihffpc
spring.rabbitmq.password=wTok4lpUhzfI6MmGNvNvAsdgzEsE4q3p
spring.rabbitmq.virtual-host=bqihffpc
spring.rabbitmq.ssl.enabled=true