spring.application.name=modulo-a-gateway
spring.datasource.url=jdbc:postgresql://db.uukodziqxvnajhucspda.supabase.co:5432/postgres?user=postgres&password=DatabaseANBIMA123!
spring.datasource.username=postgres
spring.datasource.password=DatabaseANBIMA123!

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080