name: CI Pipeline - Testes e Validação

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend-gateway:
    name: Testar Módulo A (Gateway)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modulo-a-gateway

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Rodar Testes (Maven)
        run: mvn -B test --file pom.xml

  test-backend-processor:
    name: Testar Módulo B (Processor)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modulo-b-gateway
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Rodar Testes (Maven)
        run: mvn -B test --file pom.xml

  test-frontend-angular:
    name: Testar e Buildar Frontend (Angular)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Instalar Dependências
        run: npm install

      - name: Checar Build (Angular)
        run: ng serve